# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a24b1ac9b4d216af2e009b2c4d79810d0802db3862a5edff1e053739c4b382eedca4796e286160783df833a1e1c7e3d37dd1840b2a24856be5d4c2c88b79779

test:
  secret_key_base: 72439397af0e3c941f58527076ee8d267237cb22d8a71ec828a62b56dc7d73db5c3e2103f841bf835d710514cee2621fdd4d0b9c338ffd9af57348e5df3ba20a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
